name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: v1.3.8 # Replace with the version of Terraform you want to use
        run: terraform init

      - name: Terraform Plan
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: v1.3.8 # Replace with the version of Terraform you want to use
        run: terraform plan

      - name: Terraform Apply
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: v1.3.8 # Replace with the version of Terraform you want to use
        run: terraform apply -auto-approve
